[tools]
glow = "latest"
fzf = "latest"
eza = "latest"
zoxide = "latest"
fd = "latest"
ripgrep = "latest"
starship = "latest"
bat = "latest"
yay = "latest"
usage = "latest"
python = "latest"
bun = "latest"
go = "latest"
bottom = "latest"
dust = "latest"
node = "latest"
rust = "latest"
zellij = "latest"
pnpm = "latest"
deno = "2"
neovim = "latest"
ruby = "latest"

[settings]
experimental = true
