require('impatient')
require('plugins')

require('config.keymaps')
require('config.options')

require('config.cmp')
require('config.colorizer')
require('config.dap')
require('config.feline')
require('config.inlay-hints')
require('config.mason')
require('config.rust-tools')
require('config.tabby')
require('config.telescope')
require('config.tree')
require('config.treesitter')
