require('impatient')
require('plugins')
require("mason").setup()
require("nvim-tree").setup()

require('my_config.keymaps')
require('my_config.options')
require("my_config.feline-nvim")
require("my_config.nvim-colorizer")
require("my_config.nvim-dapui")
require("my_config.nvim-telescope")
require("my_config.nvim-treesitter")
require("my_config.rust-tools")
require("my_config.cmp-nvim")
require("my_config.tabby")
